# Build settings for gfortran compiler
F90 = pgf90

#F90FLAGS += -fcheck=all -fbacktrace -ffpe-trap=invalid -g -O0

F90FLAGS += -i4 -r8 -O3 -acc -ta=tesla,cc35,maxregcount:80,nordc -Mcuda=cc35,maxregcount:80,nordc
LDFLAGS += -i4 -r8 -O3 -acc -ta=nvidia,cc35 -Mcuda=cc35,nordc
#F90FLAGS = -O3 -fopenmp


